dist_pkgdata_DATA = color.dtd	\
	colour.blue.on.dark.green.xml	\
	colour.blue.on.light.green.xml	\
	colour.default.xml	\
	colour.default.dark.xml	\
	colour.europeasian.xml	\
	colour.europeasian2.xml	\
	colour.euroasian.dark.xml	\
	colour.euroasian2.dark.xml	\
	colour.rainbow.xml	\
	colour.rainbow.dark.xml	\
	colour.thai.xml	\
	colour.thai.dark.xml	\
	colour.turbo.xml	\
	colour.turbo.dark.xml	\
	colour.vowels.xml	\
	colour.vowels.dark.xml	\
	colour.vowels2.xml	\
	colour.vowels2.dark.xml	\
	colour.yellow.on.black.xml	\
	colour.yellow.on.blue.xml
