##########################################
#        EMMA TECHNOLOGIES, L.L.C.       #
#           Copyright (c) 2013.          #
#           All rights reserved.         #
##########################################
include mk/header.mk
##########################################

INCLUDES = \
	-I.

##Make sure to define the default and clean rules for directory
default: program
clean: clean_all

##########################################
include mk/footer.mk
