##########################################
#        					Dasher				         #
#           Copyright (c) 2020.          #
#             MIT licensed							 #
#   https://opensource.org/licenses/MIT  #
##########################################
include mk/header.mk
##########################################

INCLUDES = \
	-I.

##Make sure to define the default and clean rules for directory
default: program
clean: clean_all

##########################################
include mk/footer.mk
