dist_pkgdata_DATA =			\
	training_english_GB.txt		 \
	training_wa_af_Latn.txt		 \
	training_wa_am_Ethi.txt		 \
	training_wa_ar_Arab.txt		 \
	training_wa_as_Beng.txt		 \
	training_wa_bg_Cyrl.txt		 \
	training_wa_bn_Beng.txt		 \
	training_wa_br_Latn.txt		 \
	training_wa_bs_Latn.txt		 \
	training_wa_ca_Latn.txt		 \
	training_wa_chr_Cher.txt		 \
	training_wa_co_Latn.txt		 \
	training_wa_cs_Latn.txt		 \
	training_wa_cy_Latn.txt		 \
	training_wa_da_Latn.txt		 \
	training_wa_de_Latn.txt		 \
	training_wa_ee_Latn.txt		 \
	training_wa_el_Grek.txt		 \
	training_wa_en_Latn.txt		 \
	training_wa_eo_Latn.txt		 \
	training_wa_es_Latn.txt		 \
	training_wa_et_Latn.txt		 \
	training_wa_eu_Latn.txt		 \
	training_wa_fa_Arab.txt		 \
	training_wa_fi_Latn.txt		 \
	training_wa_fo_Latn.txt		 \
	training_wa_fr_Latn.txt		 \
	training_wa_ga_Latn.txt		 \
	training_wa_gd_Latn.txt		 \
	training_wa_gl_Latn.txt		 \
	training_wa_gu_Gujr.txt		 \
	training_wa_ha_Latn.txt		 \
	training_wa_haw_Latn.txt		 \
	training_wa_he_Hebr.txt		 \
	training_wa_hr_Latn.txt		 \
	training_wa_hu_Latn.txt		 \
	training_wa_id_Latn.txt		 \
	training_wa_ig_Latn.txt		 \
	training_wa_is_Latn.txt		 \
	training_wa_it_Latn.txt		 \
	training_wa_ja_Hira.txt		 \
	training_wa_ja_Jpan.txt		 \
	training_wa_ja_Kana.txt		 \
	training_wa_ka_Geor.txt		 \
	training_wa_kk_Cyrl.txt		 \
	training_wa_kn_Knda.txt		 \
	training_wa_ko_Hang.txt		 \
	training_wa_ky_Cyrl.txt		 \
	training_wa_la_Latn.txt		 \
	training_wa_lo_Laoo.txt		 \
	training_wa_lt_Latn.txt		 \
	training_wa_mk_Cyrl.txt		 \
	training_wa_mn_Cyrl.txt		 \
	training_wa_mn_Mong.txt		 \
	training_wa_mt_Latn.txt		 \
	training_wa_my_Mymr.txt		 \
	training_wa_nl_Latn.txt		 \
	training_wa_no_Latn.txt		 \
	training_wa_oc_Latn.txt		 \
	training_wa_pa_Guru.txt		 \
	training_wa_pl_Latn.txt		 \
	training_wa_pt_Latn.txt		 \
	training_wa_rn_Latn.txt		 \
	training_wa_ro_Latn.txt		 \
	training_wa_ru_Cyrl.txt		 \
	training_wa_si_Sinh.txt		 \
	training_wa_sk_Latn.txt		 \
	training_wa_sl_Latn.txt		 \
	training_wa_so_Latn.txt		 \
	training_wa_sq_Latn.txt		 \
	training_wa_sr_Cyrl.txt		 \
	training_wa_ss_Latn.txt		 \
	training_wa_st_Latn.txt		 \
	training_wa_sv_Latn.txt		 \
	training_wa_sw_Latn.txt		 \
	training_wa_ta_Taml.txt		 \
	training_wa_te_Telu.txt		 \
	training_wa_tg_Cyrl.txt		 \
	training_wa_th_Thai.txt		 \
	training_wa_ti_Ethi.txt		 \
	training_wa_tk_Latn.txt		 \
	training_wa_tl_Latn.txt		 \
	training_wa_tn_Latn.txt		 \
	training_wa_tr_Latn.txt		 \
	training_wa_ts_Latn.txt		 \
	training_wa_uk_Cyrl.txt		 \
	training_wa_ur_Arab.txt		 \
	training_wa_uz_Latn.txt		 \
	training_wa_vi_Latn.txt		 \
	training_wa_xh_Latn.txt		 \
	training_wa_yo_Latn.txt		 \
	training_wa_zu_Latn.txt		

EXTRA_DIST =
