name: CI

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: tests/package-lock.json

      - name: Install dependencies
        working-directory: tests
        run: npm ci

      - name: Run ESLint
        working-directory: tests
        run: npm run eslint
        continue-on-error: true
